name: linter-and-tests-check

on:
  push:
    branches: [ main ]


jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install
    - name: Analysing the code with Python linters
      run: |
        make lint
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 117442324047caab71251ba36bf4afa92b8d3aed58ea1a94a1b05ed33c923c18
      with:
          coverageCommand: make test-coverage